# IGE-110420 Miguel Paiva
name: Qodana Long Parameter List

on:
  push:
    branches:
      - branch_110420
  pull_request:
    branches:
      - main

jobs:
  qodana:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write
      checks: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run Qodana
        uses: JetBrains/qodana-action@v2023.3
        with:
          args: --fail-threshold, 1
