# 12345 - Teu Nome

name: Qodana - Long Method Detection

on:
  push:
    branches:
      - main
      - branch_123779
  pull_request:

jobs:
  qodana:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Qodana
        uses: JetBrains/qodana-action@v2023.2
        with:
          args: --save-report
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}